### ISSUE TITLE
Complete Use Case 2 : Navigate and explore vocab dictionary.

### ISSUE THREAD

**Issue by janro13806** [COS301-SE-2023/WordWizard#22]
Navigate and Explore Vocab Dictionary:
In this use case, the system provides functionality for users to navigate and explore the vocabulary dictionary. Users should be able to access the dictionary, which contains a collection of words and their associated definitions. The system should present the dictionary in an organized and user-friendly manner, allowing users to search for specific words, browse through entries alphabetically, and potentially filter words based on different criteria (e.g., word category, difficulty level). The user should be able to view detailed information about each word, including its definition, pronunciation, and any additional relevant details.

**Comment by Prometheus18082106** [comment]
Basic page structure completed

**Comment by Prometheus18082106** [comment]
Scroll subcomponent implemented and functional - needs some styling
